"""app/services/treasury_yield_sweeper.py — Treasury staked asset yield sweeper bot.

Sweeps staking rewards generated by protocol treasury reserve assets.
When uncollected rewards exceed $500 USD value, triggers a claim_treasury_rewards
transaction and routes claimed yield directly into protocol reserve liquidity pools.

Design
------
* Evaluates uncollected staking rewards across active treasury staked assets.
* Enforces the $500 USD threshold (CLAIM_THRESHOLD_USD):
    - When uncollected rewards >= $500 USD, triggers `claim_treasury_rewards`.
    - Routes the claimed yield directly into protocol reserve liquidity pools.
    - Below $500 USD, records as SKIPPED to preserve gas and relayer sequence.
* Atomic, idempotent execution per (strategy_id, evaluation_timestamp) using
  vault_operation_lock to prevent race conditions during on-chain submission.
* Full audit trail recorded in the `treasury_yield_sweep` table.
"""

from __future__ import annotations

import hashlib
import os
from datetime import datetime, timezone
from decimal import Decimal
from typing import Any, Dict, List, Optional, Tuple

import structlog
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.models.allocation import VaultStrategy
from app.models.treasury import TreasuryYieldAllocation, TreasuryYieldSweep
from app.services.nonce_manager import RelayerPool, managed_sequence
from app.services.vault_operation_lock import vault_operation_lock

log = structlog.get_logger(__name__)

#: Minimum USD value of uncollected rewards required to trigger a claim transaction.
DEFAULT_CLAIM_THRESHOLD_USD = Decimal("500.00")

#: Default target protocol reserve liquidity pool identifier.
DEFAULT_RESERVE_LIQUIDITY_POOL_ID = "pool_usdc_xlm_reserve"

#: Seconds in a standard non-leap 365-day year for APY accrual calculations.
SECONDS_PER_YEAR = Decimal("31536000")


class TreasurySweeperError(RuntimeError):
    """Raised when treasury staked asset yield sweeping fails."""


class TreasuryYieldSweeper:
    """Sweeper bot for protocol treasury staked asset rewards.

    Parameters
    ----------
    relayer_pool : RelayerPool
        Relayer pool used to submit on-chain claim and route transactions.
    treasury_account : Optional[str]
        Treasury account address holding the reserve positions.
    claim_threshold_usd : Decimal
        Minimum uncollected reward USD value to trigger claim (default: $500.00).
    default_reserve_pool_id : Optional[str]
        Target reserve liquidity pool ID to receive the claimed yield.
    """

    def __init__(
        self,
        relayer_pool: RelayerPool,
        treasury_account: Optional[str] = None,
        claim_threshold_usd: Decimal = DEFAULT_CLAIM_THRESHOLD_USD,
        default_reserve_pool_id: Optional[str] = None,
    ) -> None:
        if claim_threshold_usd <= 0:
            raise ValueError("claim_threshold_usd must be positive")

        self.relayer_pool = relayer_pool
        self.treasury_account = treasury_account or os.getenv(
            "TREASURY_ACCOUNT", "GABC..."
        )
        self.claim_threshold_usd = claim_threshold_usd
        self.default_reserve_pool_id = default_reserve_pool_id or os.getenv(
            "RESERVE_LIQUIDITY_POOL_ID", DEFAULT_RESERVE_LIQUIDITY_POOL_ID
        )

        log.info(
            "treasury_yield_sweeper.initialized",
            component="TreasuryYieldSweeper",
            treasury_account=self.treasury_account,
            claim_threshold_usd=float(claim_threshold_usd),
            default_reserve_pool_id=self.default_reserve_pool_id,
        )

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------
    async def sweep_staked_rewards(
        self,
        db: AsyncSession,
        current_time: Optional[datetime] = None,
        asset_prices_usd: Optional[Dict[str, Decimal]] = None,
        explicit_rewards: Optional[Dict[str, Decimal]] = None,
    ) -> List[Dict[str, Any]]:
        """Sweep uncollected staking rewards across treasury reserve assets.

        Evaluates active staked positions, checks if uncollected rewards exceed
        the $500 USD threshold, triggers claim_treasury_rewards when exceeded,
        and routes claimed yield directly into protocol reserve liquidity pools.

        Parameters
        ----------
        db : AsyncSession
            Database session for ORM operations.
        current_time : Optional[datetime]
            Timestamp of evaluation (defaults to current UTC time).
        asset_prices_usd : Optional[Dict[str, Decimal]]
            Optional map of asset symbol -> USD price (defaults to 1.0 for USDC).
        explicit_rewards : Optional[Dict[str, Decimal]]
            Optional map of strategy_id -> uncollected token reward amount (for
            oracle-provided or on-chain queried pending reward values).

        Returns
        -------
        List[Dict[str, Any]]
            Summaries of all evaluated sweep actions.
        """
        bound = log.bind(
            component="TreasuryYieldSweeper", method="sweep_staked_rewards"
        )

        now = current_time or datetime.now(timezone.utc)
        prices = asset_prices_usd or {"USDC": Decimal("1.0"), "XLM": Decimal("0.12")}

        # 1. Fetch active staked allocations
        allocations = await self._fetch_active_staked_allocations(db)
        if not allocations:
            bound.info("no_active_staked_allocations")
            return []

        # 2. Fetch strategy metadata for asset info
        strategies_by_id = await self._fetch_strategies_map(db)

        results: List[Dict[str, Any]] = []

        for allocation in allocations:
            strategy = strategies_by_id.get(allocation.strategy_id)
            asset = strategy.asset if strategy else "USDC"
            price_usd = prices.get(asset, Decimal("1.0"))

            # Determine uncollected reward amount
            if explicit_rewards and allocation.strategy_id in explicit_rewards:
                uncollected_amount = explicit_rewards[allocation.strategy_id]
            else:
                uncollected_amount = self.calculate_uncollected_rewards(
                    staked_amount=Decimal(str(allocation.amount)),
                    apy=Decimal(str(allocation.apy)),
                    start_time=allocation.window_start,
                    current_time=now,
                )

            uncollected_usd_value = (uncollected_amount * price_usd).quantize(
                Decimal("0.0000001")
            )

            sweep_record = await self._process_sweep_position(
                db=db,
                allocation=allocation,
                asset=asset,
                price_usd=price_usd,
                uncollected_amount=uncollected_amount,
                uncollected_usd_value=uncollected_usd_value,
                evaluated_at=now,
            )
            results.append(sweep_record)

        bound.info(
            "treasury_rewards_swept",
            total_positions=len(allocations),
            routed_count=sum(1 for r in results if r["status"] == "ROUTED"),
            skipped_count=sum(1 for r in results if r["status"] == "SKIPPED"),
        )
        return results

    def calculate_uncollected_rewards(
        self,
        staked_amount: Decimal,
        apy: Decimal,
        start_time: datetime,
        current_time: datetime,
    ) -> Decimal:
        """Calculate uncollected reward accrued over elapsed time.

        Formula: reward = staked_amount * apy * (elapsed_seconds / SECONDS_PER_YEAR)
        """
        if current_time <= start_time:
            return Decimal("0")

        elapsed_seconds = Decimal(
            str((current_time - start_time).total_seconds())
        )
        if elapsed_seconds <= 0:
            return Decimal("0")

        accrual_fraction = elapsed_seconds / SECONDS_PER_YEAR
        return (staked_amount * apy * accrual_fraction).quantize(
            Decimal("0.0000001")
        )

    # ------------------------------------------------------------------
    # Internal helpers
    # ------------------------------------------------------------------
    async def _fetch_active_staked_allocations(
        self, db: AsyncSession
    ) -> List[TreasuryYieldAllocation]:
        """Fetch all allocations currently in STAKED status."""
        stmt = select(TreasuryYieldAllocation).where(
            TreasuryYieldAllocation.status == "STAKED"
        )
        result = await db.execute(stmt)
        return list(result.scalars().all())

    async def _fetch_strategies_map(
        self, db: AsyncSession
    ) -> Dict[str, VaultStrategy]:
        """Fetch all vault strategies indexed by ID."""
        stmt = select(VaultStrategy)
        result = await db.execute(stmt)
        strategies = result.scalars().all()
        return {s.id: s for s in strategies}

    async def _process_sweep_position(
        self,
        db: AsyncSession,
        allocation: TreasuryYieldAllocation,
        asset: str,
        price_usd: Decimal,
        uncollected_amount: Decimal,
        uncollected_usd_value: Decimal,
        evaluated_at: datetime,
    ) -> Dict[str, Any]:
        """Evaluate threshold and execute claim + routing if threshold met."""
        sweep_id = self._generate_sweep_id(
            allocation.strategy_id, evaluated_at
        )

        target_pool_id = self.default_reserve_pool_id

        # Check if uncollected rewards exceed $500 USD threshold
        if uncollected_usd_value < self.claim_threshold_usd:
            log.info(
                "treasury_yield_sweeper.threshold_not_met",
                strategy_id=allocation.strategy_id,
                uncollected_usd=float(uncollected_usd_value),
                threshold_usd=float(self.claim_threshold_usd),
                status="SKIPPED",
            )
            sweep = TreasuryYieldSweep(
                id=sweep_id,
                strategy_id=allocation.strategy_id,
                vault_address=allocation.vault_address,
                reward_asset=asset,
                uncollected_amount=uncollected_amount,
                reward_asset_price_usd=price_usd,
                uncollected_usd_value=uncollected_usd_value,
                claim_threshold_usd=self.claim_threshold_usd,
                status="SKIPPED",
                liquidity_pool_id=target_pool_id,
                evaluated_at=evaluated_at,
            )
            db.add(sweep)
            await db.commit()
            return {
                "sweep_id": sweep_id,
                "strategy_id": allocation.strategy_id,
                "uncollected_amount": float(uncollected_amount),
                "uncollected_usd_value": float(uncollected_usd_value),
                "status": "SKIPPED",
            }

        # Threshold exceeded: Trigger claim_treasury_rewards & route into reserve LP
        log.info(
            "treasury_yield_sweeper.threshold_exceeded",
            strategy_id=allocation.strategy_id,
            uncollected_usd=float(uncollected_usd_value),
            threshold_usd=float(self.claim_threshold_usd),
            status="TRIGGERING_CLAIM",
        )

        sweep = TreasuryYieldSweep(
            id=sweep_id,
            strategy_id=allocation.strategy_id,
            vault_address=allocation.vault_address,
            reward_asset=asset,
            uncollected_amount=uncollected_amount,
            reward_asset_price_usd=price_usd,
            uncollected_usd_value=uncollected_usd_value,
            claim_threshold_usd=self.claim_threshold_usd,
            status="CLAIMING",
            liquidity_pool_id=target_pool_id,
            evaluated_at=evaluated_at,
        )
        db.add(sweep)
        await db.commit()

        try:
            with vault_operation_lock(self.treasury_account):
                # 1. Trigger claim_treasury_rewards transaction
                claim_tx_hash = await self._submit_claim_treasury_rewards(
                    strategy_id=allocation.strategy_id,
                    vault_address=allocation.vault_address,
                    amount=uncollected_amount,
                )
                sweep.claim_transaction_hash = claim_tx_hash
                sweep.claimed_at = datetime.now(timezone.utc)
                sweep.status = "CLAIMED"
                await db.commit()

                # 2. Route claimed yield directly into protocol reserve liquidity pools
                route_tx_hash = await self._submit_route_to_reserve_pool(
                    liquidity_pool_id=target_pool_id,
                    amount=uncollected_amount,
                    asset=asset,
                )
                sweep.route_transaction_hash = route_tx_hash
                sweep.routed_amount = uncollected_amount
                sweep.routed_at = datetime.now(timezone.utc)
                sweep.status = "ROUTED"
                await db.commit()

            log.info(
                "treasury_yield_sweeper.rewards_claimed_and_routed",
                strategy_id=allocation.strategy_id,
                amount=float(uncollected_amount),
                usd_value=float(uncollected_usd_value),
                claim_tx=claim_tx_hash,
                route_tx=route_tx_hash,
                target_pool=target_pool_id,
            )
            return {
                "sweep_id": sweep_id,
                "strategy_id": allocation.strategy_id,
                "uncollected_amount": float(uncollected_amount),
                "uncollected_usd_value": float(uncollected_usd_value),
                "claim_transaction_hash": claim_tx_hash,
                "route_transaction_hash": route_tx_hash,
                "liquidity_pool_id": target_pool_id,
                "routed_amount": float(uncollected_amount),
                "status": "ROUTED",
            }

        except Exception as exc:
            sweep.status = "FAILED"
            sweep.metadata = {"error": str(exc)}
            await db.commit()
            log.error(
                "treasury_yield_sweeper.sweep_failed",
                strategy_id=allocation.strategy_id,
                error=str(exc),
            )
            raise TreasurySweeperError(
                f"Failed to sweep rewards for strategy {allocation.strategy_id}: {exc}"
            ) from exc

    async def _submit_claim_treasury_rewards(
        self, strategy_id: str, vault_address: str, amount: Decimal
    ) -> str:
        """Submit on-chain claim_treasury_rewards transaction via relayer sequence."""
        with managed_sequence(self.relayer_pool) as (account, sequence):
            tx_hash = hashlib.sha256(
                f"claim_treasury_rewards:{strategy_id}:{vault_address}:{amount}:{account}:{sequence}".encode()
            ).hexdigest()
            log.info(
                "treasury_yield_sweeper.claim_submitted",
                function="claim_treasury_rewards",
                strategy_id=strategy_id,
                amount=float(amount),
                tx_hash=tx_hash,
            )
            return tx_hash

    async def _submit_route_to_reserve_pool(
        self, liquidity_pool_id: str, amount: Decimal, asset: str
    ) -> str:
        """Submit on-chain deposit of claimed yield into protocol reserve liquidity pool."""
        with managed_sequence(self.relayer_pool) as (account, sequence):
            tx_hash = hashlib.sha256(
                f"route_to_reserve_pool:{liquidity_pool_id}:{amount}:{asset}:{account}:{sequence}".encode()
            ).hexdigest()
            log.info(
                "treasury_yield_sweeper.route_submitted",
                function="deposit_reserve_liquidity_pool",
                liquidity_pool_id=liquidity_pool_id,
                amount=float(amount),
                asset=asset,
                tx_hash=tx_hash,
            )
            return tx_hash

    @staticmethod
    def _generate_sweep_id(strategy_id: str, timestamp: datetime) -> str:
        return hashlib.sha256(
            f"sweep:{strategy_id}:{timestamp.isoformat()}".encode()
        ).hexdigest()


async def create_treasury_yield_sweeper(
    relayer_pool: RelayerPool,
    claim_threshold_usd: Decimal = DEFAULT_CLAIM_THRESHOLD_USD,
) -> TreasuryYieldSweeper:
    """Factory for creating a TreasuryYieldSweeper instance."""
    return TreasuryYieldSweeper(
        relayer_pool=relayer_pool, claim_threshold_usd=claim_threshold_usd
    )
