import { getRedisClient } from "../lib/redis";
import {
  getStellarNetwork,
  getStellarNetworkPassphrase,
} from "../lib/stellarNetwork";
import { logger } from "../utils/logger";

/**
 * Issue #1040 – SEP-01 Stellar TOML Configuration File Auto-Generator.
 *
 * Generates a SEP-01 compliant `/.well-known/stellar.toml` from live backend
 * configuration: active contract addresses, anchor endpoints and supported
 * asset codes. The generated document is cached in Redis for one hour so the
 * well-known endpoint stays cheap under load.
 */

export interface Sep01Currency {
  code: string;
  issuer?: string;
  name?: string;
  description?: string;
  displayDecimals?: number;
  anchorAsset?: string;
  status?: string;
}

export interface Sep01Anchor {
  name: string;
  url: string;
  protocols?: string[];
}

export interface Sep01Principal {
  name: string;
  email?: string;
  url?: string;
}

export interface Sep01Documentation {
  orgName: string;
  orgUrl: string;
  orgDescription?: string;
  orgOfficialEmail?: string;
  orgSupportEmail?: string;
  orgGithub?: string;
}

export interface Sep01TomlConfig {
  version: string;
  networkPassphrase: string;
  accounts: string[];
  signingKey?: string;
  webAuthEndpoint?: string;
  horizonUrl?: string;
  transferServerSep24?: string;
  documentation: Sep01Documentation;
  principals: Sep01Principal[];
  currencies: Sep01Currency[];
  contracts: Record<string, string>;
  anchors: Sep01Anchor[];
}

export const SEP01_TOML_CACHE_KEY = "stellarflow:sep01:stellar.toml";
export const SEP01_TOML_CACHE_TTL_SECONDS = 3600;

export interface Sep01TomlResult {
  toml: string;
  cached: boolean;
  expiresInSeconds: number;
}

export type Sep01AssetLoader = () => Promise<Sep01Currency[]>;

function tomlString(value: string): string {
  return `"${value
    .replace(/\\/g, "\\\\")
    .replace(/"/g, '\\"')
    .replace(/\n/g, "\\n")}"`;
}

function tomlStringArray(values: string[]): string {
  return `[${values.map(tomlString).join(", ")}]`;
}

function pushKey(lines: string[], key: string, value: string | undefined): void {
  if (value !== undefined && value !== "") {
    lines.push(`${key} = ${tomlString(value)}`);
  }
}

/**
 * Render a SEP-01 `stellar.toml`. Standard sections are emitted first, then a
 * `[STELLARFLOW]` extension table carries contract addresses and anchor
 * endpoints that SEP-01 itself does not define.
 */
export function renderStellarToml(config: Sep01TomlConfig): string {
  const lines: string[] = [
    "# SEP-01 stellar.toml generated by StellarFlow",
    "# https://github.com/StellarFlow-Network/stellarflow-backend",
    `VERSION = ${tomlString(config.version)}`,
    `NETWORK_PASSPHRASE = ${tomlString(config.networkPassphrase)}`,
  ];

  if (config.accounts.length > 0) {
    lines.push(`ACCOUNTS = ${tomlStringArray(config.accounts)}`);
  }
  pushKey(lines, "SIGNING_KEY", config.signingKey);
  pushKey(lines, "WEB_AUTH_ENDPOINT", config.webAuthEndpoint);
  pushKey(lines, "HORIZON_URL", config.horizonUrl);
  pushKey(lines, "TRANSFER_SERVER_SEP0024", config.transferServerSep24);

  lines.push("");
  lines.push("[DOCUMENTATION]");
  pushKey(lines, "ORG_NAME", config.documentation.orgName);
  pushKey(lines, "ORG_URL", config.documentation.orgUrl);
  pushKey(lines, "ORG_DESCRIPTION", config.documentation.orgDescription);
  pushKey(lines, "ORG_OFFICIAL_EMAIL", config.documentation.orgOfficialEmail);
  pushKey(lines, "ORG_SUPPORT_EMAIL", config.documentation.orgSupportEmail);
  pushKey(lines, "ORG_GITHUB", config.documentation.orgGithub);

  for (const principal of config.principals) {
    lines.push("");
    lines.push("[[PRINCIPALS]]");
    pushKey(lines, "name", principal.name);
    pushKey(lines, "email", principal.email);
    pushKey(lines, "url", principal.url);
  }

  for (const currency of config.currencies) {
    lines.push("");
    lines.push("[[CURRENCIES]]");
    pushKey(lines, "code", currency.code);
    pushKey(lines, "issuer", currency.issuer);
    pushKey(lines, "name", currency.name);
    pushKey(lines, "desc", currency.description);
    pushKey(lines, "anchor_asset", currency.anchorAsset);
    pushKey(lines, "status", currency.status);
    lines.push(
      `display_decimals = ${currency.displayDecimals ?? 7}`,
    );
  }

  lines.push("");
  lines.push("[STELLARFLOW]");
  lines.push(`version = ${tomlString(config.version)}`);
  lines.push(`network = ${tomlString(getStellarNetwork())}`);

  const contractEntries = Object.entries(config.contracts);
  if (contractEntries.length > 0) {
    lines.push("");
    lines.push("[STELLARFLOW.CONTRACTS]");
    for (const [name, address] of contractEntries) {
      lines.push(`${name} = ${tomlString(address)}`);
    }
  }

  for (const anchor of config.anchors) {
    lines.push("");
    lines.push("[[STELLARFLOW.ANCHORS]]");
    pushKey(lines, "name", anchor.name);
    pushKey(lines, "url", anchor.url);
    if (anchor.protocols && anchor.protocols.length > 0) {
      lines.push(`protocols = ${tomlStringArray(anchor.protocols)}`);
    }
  }

  return `${lines.join("\n")}\n`;
}

function parseJsonArray<T>(raw: string | undefined): T[] {
  if (!raw) return [];
  try {
    const parsed = JSON.parse(raw);
    return Array.isArray(parsed) ? (parsed as T[]) : [];
  } catch {
    return [];
  }
}

function parseIssuers(): Record<string, string> {
  const map: Record<string, string> = {};
  for (const [key, value] of Object.entries(process.env)) {
    if (key.startsWith("SEP01_ASSET_ISSUER_") && value) {
      map[key.slice("SEP01_ASSET_ISSUER_".length).toUpperCase()] = value;
    }
  }
  return map;
}

function collectContracts(): Record<string, string> {
  const contracts: Record<string, string> = {};
  const candidates: Array<[string, string | undefined]> = [
    ["oracle", process.env.CONTRACT_ID],
    ["bridge", process.env.SOROBAN_BRIDGE_CONTRACT_ID],
    ["flashLoan", process.env.FLASH_LOAN_CONTRACT_ID],
    ["rebalancing", process.env.REBALANCING_CONTRACT_ID],
  ];
  for (const [name, value] of candidates) {
    if (value && value.trim() !== "") contracts[name] = value.trim();
  }
  for (const [key, value] of Object.entries(process.env)) {
    if (key.startsWith("SEP01_CONTRACT_") && value && value.trim() !== "") {
      contracts[key.slice("SEP01_CONTRACT_".length).toLowerCase()] = value.trim();
    }
  }
  return contracts;
}

function collectAnchors(): Sep01Anchor[] {
  const configured = parseJsonArray<Sep01Anchor>(
    process.env.SEP01_ANCHOR_ENDPOINTS,
  );
  const anchors = configured.filter(
    (anchor) => anchor && typeof anchor.url === "string",
  );

  const sep24 = process.env.ANCHOR_SEP24_STATUS_URL?.trim();
  if (sep24 && !anchors.some((anchor) => anchor.url === sep24)) {
    anchors.push({ name: "SEP-24 anchor", url: sep24, protocols: ["SEP-24"] });
  }
  const sep31 = process.env.ANCHOR_SEP31_STATUS_URL?.trim();
  if (sep31 && !anchors.some((anchor) => anchor.url === sep31)) {
    anchors.push({ name: "SEP-31 anchor", url: sep31, protocols: ["SEP-31"] });
  }
  return anchors;
}

const defaultAssetLoader: Sep01AssetLoader = async () => {
  try {
    const { default: prisma } = await import("../lib/prisma");
    const rows = await (prisma as any).currency.findMany({
      where: { isActive: true },
      select: { code: true, name: true },
      orderBy: { code: "asc" },
    });
    const issuers = parseIssuers();
    return (rows as Array<{ code: string; name: string }>).map((row) => {
      const currency: Sep01Currency = {
        code: row.code,
        name: row.name,
        displayDecimals: 7,
      };
      const issuer = issuers[row.code.toUpperCase()];
      if (issuer) currency.issuer = issuer;
      return currency;
    });
  } catch (error) {
    logger.warn(
      `[Sep01TomlService] Falling back to configured assets: ${
        error instanceof Error ? error.message : String(error)
      }`,
    );
    return [];
  }
};

export interface Sep01TomlServiceDeps {
  getRedis?: typeof getRedisClient;
  loadAssets?: Sep01AssetLoader;
  ttlSeconds?: number;
}

export class Sep01TomlService {
  private readonly redisProvider: typeof getRedisClient;
  private readonly loadAssets: Sep01AssetLoader;
  private readonly ttlSeconds: number;

  constructor(deps: Sep01TomlServiceDeps = {}) {
    this.redisProvider = deps.getRedis ?? getRedisClient;
    this.loadAssets = deps.loadAssets ?? defaultAssetLoader;
    this.ttlSeconds = deps.ttlSeconds ?? SEP01_TOML_CACHE_TTL_SECONDS;
  }

  async buildConfig(): Promise<Sep01TomlConfig> {
    const accounts = [
      process.env.STELLAR_PUBLIC_KEY,
      process.env.GAS_ACCOUNT_PUBLIC_KEY,
    ].filter((value): value is string => Boolean(value && value.trim()));

    const assets = await this.loadAssets();
    const currencies: Sep01Currency[] =
      assets.length > 0
        ? assets
        : [
            { code: "XLM", name: "Stellar Lumens", displayDecimals: 7 },
            { code: "USDC", name: "USD Coin", displayDecimals: 7 },
          ];

    const config: Sep01TomlConfig = {
      version: process.env.SEP01_TOML_VERSION ?? "1.0.0",
      networkPassphrase: getStellarNetworkPassphrase(),
      accounts,
      documentation: {
        orgName: process.env.SEP01_ORG_NAME ?? "StellarFlow",
        orgUrl: process.env.SEP01_ORG_URL ?? "https://stellarflow.io",
        orgGithub: "https://github.com/StellarFlow-Network/stellarflow-backend",
      },
      principals: parseJsonArray<Sep01Principal>(process.env.SEP01_PRINCIPALS),
      currencies,
      contracts: collectContracts(),
      anchors: collectAnchors(),
    };

    const signingKey = process.env.STELLAR_PUBLIC_KEY?.trim();
    if (signingKey) config.signingKey = signingKey;
    const webAuth = process.env.SEP01_WEB_AUTH_ENDPOINT?.trim();
    if (webAuth) config.webAuthEndpoint = webAuth;
    const horizon = process.env.HORIZON_URL?.trim();
    if (horizon) config.horizonUrl = horizon;
    const transferServer = process.env.ANCHOR_SEP24_STATUS_URL?.trim();
    if (transferServer) config.transferServerSep24 = transferServer;
    const description = process.env.SEP01_ORG_DESCRIPTION?.trim();
    if (description) config.documentation.orgDescription = description;
    const email = process.env.SEP01_ORG_EMAIL?.trim();
    if (email) config.documentation.orgOfficialEmail = email;

    return config;
  }

  async generate(): Promise<string> {
    return renderStellarToml(await this.buildConfig());
  }

  async getToml(): Promise<Sep01TomlResult> {
    const redis = this.redisProvider();
    if (redis?.isOpen) {
      try {
        const cached = await redis.get(SEP01_TOML_CACHE_KEY);
        if (cached) {
          const ttl = await redis.ttl(SEP01_TOML_CACHE_KEY);
          return {
            toml: cached,
            cached: true,
            expiresInSeconds: ttl > 0 ? ttl : this.ttlSeconds,
          };
        }
      } catch (error) {
        logger.warn(
          `[Sep01TomlService] Redis read failed: ${
            error instanceof Error ? error.message : String(error)
          }`,
        );
      }
    }

    const toml = await this.generate();

    if (redis?.isOpen) {
      try {
        await redis.setEx(SEP01_TOML_CACHE_KEY, this.ttlSeconds, toml);
      } catch (error) {
        logger.warn(
          `[Sep01TomlService] Redis write failed: ${
            error instanceof Error ? error.message : String(error)
          }`,
        );
      }
    }

    return { toml, cached: false, expiresInSeconds: this.ttlSeconds };
  }

  async invalidate(): Promise<void> {
    const redis = this.redisProvider();
    if (!redis?.isOpen) return;
    try {
      await redis.del(SEP01_TOML_CACHE_KEY);
    } catch (error) {
      logger.warn(
        `[Sep01TomlService] Redis delete failed: ${
          error instanceof Error ? error.message : String(error)
        }`,
      );
    }
  }
}

export const sep01TomlService = new Sep01TomlService();
