/**
 * src/services/treasuryYieldSweeperService.ts
 *
 * Treasury Staked Asset Yield Sweeper Bot (Issue #974).
 *
 * Requirements:
 * - Sweep staking rewards generated by protocol treasury reserve assets.
 * - Trigger `claim_treasury_rewards` transaction when uncollected rewards exceed $500 USD value.
 * - Route claimed yield directly into protocol reserve liquidity pools.
 */

export type SweepExecutionStatus = "CLAIMED_AND_ROUTED" | "SKIPPED" | "FAILED";

export interface TreasuryStakedPosition {
  strategyId: string;
  vaultAddress: string;
  asset: string;
  stakedAmount: number;
  uncollectedRewards: number;
  rewardAssetPriceUsd: number;
  reservePoolId?: string;
}

export interface TreasuryStakedPositionsSource {
  getStakedPositions(): Promise<TreasuryStakedPosition[]>;
}

export interface TreasuryClaimResult {
  transactionHash: string;
  claimedAmount: number;
}

export interface TreasuryClaimExecutor {
  claim_treasury_rewards(
    strategyId: string,
    vaultAddress: string,
    amount: number,
  ): Promise<TreasuryClaimResult>;
}

export interface ReservePoolRoutingResult {
  transactionHash: string;
  routedAmount: number;
  poolId: string;
}

export interface ReserveLiquidityPoolRouter {
  routeToReservePool(
    poolId: string,
    asset: string,
    amount: number,
  ): Promise<ReservePoolRoutingResult>;
}

export interface TreasurySweepRecord {
  strategyId: string;
  vaultAddress: string;
  asset: string;
  stakedAmount: number;
  uncollectedAmount: number;
  rewardAssetPriceUsd: number;
  uncollectedUsdValue: number;
  claimThresholdUsd: number;
  status: SweepExecutionStatus;
  claimTransactionHash?: string;
  routeTransactionHash?: string;
  reservePoolId?: string;
  evaluatedAt: Date;
  executedAt?: Date;
  error?: string;
}

export interface TreasurySweeperAnalyticsRepository {
  recordSweep(record: TreasurySweepRecord): Promise<void>;
}

export interface TreasurySweepEvaluation {
  strategyId: string;
  vaultAddress: string;
  asset: string;
  uncollectedRewards: number;
  uncollectedUsdValue: number;
  status: SweepExecutionStatus;
  claimTransactionHash?: string;
  routeTransactionHash?: string;
  reservePoolId?: string;
  error?: string;
}

export const DEFAULT_CLAIM_THRESHOLD_USD = 500;
export const DEFAULT_RESERVE_LIQUIDITY_POOL_ID = "pool_usdc_xlm_reserve";
export const DEFAULT_SWEEPER_INTERVAL_MS = 60_000;

export class TreasuryStakedAssetYieldSweeperBot {
  private timer: ReturnType<typeof setInterval> | undefined;
  private sweeping = false;

  constructor(
    private readonly source: TreasuryStakedPositionsSource,
    private readonly claimExecutor: TreasuryClaimExecutor,
    private readonly poolRouter: ReserveLiquidityPoolRouter,
    private readonly analytics?: TreasurySweeperAnalyticsRepository,
    private readonly claimThresholdUsd: number = Number(
      process.env.TREASURY_SWEEPER_CLAIM_THRESHOLD_USD ?? DEFAULT_CLAIM_THRESHOLD_USD,
    ),
    private readonly defaultReservePoolId: string = process.env
      .RESERVE_LIQUIDITY_POOL_ID ?? DEFAULT_RESERVE_LIQUIDITY_POOL_ID,
    private readonly intervalMs: number = Number(
      process.env.TREASURY_SWEEPER_INTERVAL_MS ?? DEFAULT_SWEEPER_INTERVAL_MS,
    ),
  ) {
    if (!Number.isFinite(claimThresholdUsd) || claimThresholdUsd <= 0) {
      throw new Error("Treasury sweeper claim threshold USD must be a positive number");
    }
    if (!Number.isFinite(intervalMs) || intervalMs <= 0) {
      throw new Error("Treasury sweeper interval must be positive");
    }
  }

  start(): void {
    if (this.timer) return;
    void this.sweep();
    this.timer = setInterval(() => void this.sweep(), this.intervalMs);
    this.timer.unref?.();
  }

  stop(): void {
    if (this.timer) clearInterval(this.timer);
    this.timer = undefined;
  }

  async sweep(): Promise<TreasurySweepEvaluation[]> {
    if (this.sweeping) return [];
    this.sweeping = true;

    try {
      const positions = await this.source.getStakedPositions();
      return await Promise.all(
        positions.map((position) => this.evaluatePosition(position)),
      );
    } finally {
      this.sweeping = false;
    }
  }

  private async evaluatePosition(
    position: TreasuryStakedPosition,
  ): Promise<TreasurySweepEvaluation> {
    this.validatePosition(position);

    const evaluatedAt = new Date();
    const uncollectedUsdValue =
      position.uncollectedRewards * position.rewardAssetPriceUsd;
    const targetPoolId = position.reservePoolId ?? this.defaultReservePoolId;

    // Trigger claim_treasury_rewards only when uncollected rewards exceed $500 USD value
    if (uncollectedUsdValue <= this.claimThresholdUsd) {
      const record: TreasurySweepRecord = {
        strategyId: position.strategyId,
        vaultAddress: position.vaultAddress,
        asset: position.asset,
        stakedAmount: position.stakedAmount,
        uncollectedAmount: position.uncollectedRewards,
        rewardAssetPriceUsd: position.rewardAssetPriceUsd,
        uncollectedUsdValue,
        claimThresholdUsd: this.claimThresholdUsd,
        status: "SKIPPED",
        reservePoolId: targetPoolId,
        evaluatedAt,
      };
      await this.analytics?.recordSweep(record);

      return {
        strategyId: position.strategyId,
        vaultAddress: position.vaultAddress,
        asset: position.asset,
        uncollectedRewards: position.uncollectedRewards,
        uncollectedUsdValue,
        status: "SKIPPED",
        reservePoolId: targetPoolId,
      };
    }

    try {
      // 1. Trigger claim_treasury_rewards transaction
      const claimResult = await this.claimExecutor.claim_treasury_rewards(
        position.strategyId,
        position.vaultAddress,
        position.uncollectedRewards,
      );

      // 2. Route claimed yield directly into protocol reserve liquidity pools
      const routeResult = await this.poolRouter.routeToReservePool(
        targetPoolId,
        position.asset,
        position.uncollectedRewards,
      );

      const executedAt = new Date();
      const record: TreasurySweepRecord = {
        strategyId: position.strategyId,
        vaultAddress: position.vaultAddress,
        asset: position.asset,
        stakedAmount: position.stakedAmount,
        uncollectedAmount: position.uncollectedRewards,
        rewardAssetPriceUsd: position.rewardAssetPriceUsd,
        uncollectedUsdValue,
        claimThresholdUsd: this.claimThresholdUsd,
        status: "CLAIMED_AND_ROUTED",
        claimTransactionHash: claimResult.transactionHash,
        routeTransactionHash: routeResult.transactionHash,
        reservePoolId: targetPoolId,
        evaluatedAt,
        executedAt,
      };
      await this.analytics?.recordSweep(record);

      return {
        strategyId: position.strategyId,
        vaultAddress: position.vaultAddress,
        asset: position.asset,
        uncollectedRewards: position.uncollectedRewards,
        uncollectedUsdValue,
        status: "CLAIMED_AND_ROUTED",
        claimTransactionHash: claimResult.transactionHash,
        routeTransactionHash: routeResult.transactionHash,
        reservePoolId: targetPoolId,
      };
    } catch (error) {
      const message = error instanceof Error ? error.message : String(error);
      const record: TreasurySweepRecord = {
        strategyId: position.strategyId,
        vaultAddress: position.vaultAddress,
        asset: position.asset,
        stakedAmount: position.stakedAmount,
        uncollectedAmount: position.uncollectedRewards,
        rewardAssetPriceUsd: position.rewardAssetPriceUsd,
        uncollectedUsdValue,
        claimThresholdUsd: this.claimThresholdUsd,
        status: "FAILED",
        reservePoolId: targetPoolId,
        error: message,
        evaluatedAt,
      };
      await this.analytics?.recordSweep(record);

      return {
        strategyId: position.strategyId,
        vaultAddress: position.vaultAddress,
        asset: position.asset,
        uncollectedRewards: position.uncollectedRewards,
        uncollectedUsdValue,
        status: "FAILED",
        reservePoolId: targetPoolId,
        error: message,
      };
    }
  }

  private validatePosition(position: TreasuryStakedPosition): void {
    if (!position.strategyId || !position.vaultAddress || !position.asset) {
      throw new Error("Treasury staked position requires strategyId, vaultAddress, and asset");
    }
    if (
      !Number.isFinite(position.stakedAmount) ||
      !Number.isFinite(position.uncollectedRewards) ||
      !Number.isFinite(position.rewardAssetPriceUsd) ||
      position.stakedAmount < 0 ||
      position.uncollectedRewards < 0 ||
      position.rewardAssetPriceUsd < 0
    ) {
      throw new Error("Staked position amounts and prices must be finite, non-negative numbers");
    }
  }
}
