#!/usr/bin/env python3
"""
Compile Protocol Buffer definitions to Python modules.

This script compiles .proto files in the proto/ directory into Python
code that can be imported by the application. The generated files are
placed in app/proto_generated/.

Usage:
    python scripts/compile_proto.py

Requirements:
    - protobuf>=4.25.0
    - grpcio-tools>=1.60.0

Install dependencies first:
    pip install -r requirements.txt
"""

import sys
from pathlib import Path


def compile_proto_files():
    """Compile all .proto files to Python."""
    # Check if grpc_tools is available
    try:
        from grpc_tools import protoc
    except ImportError:
        print("❌ Error: grpcio-tools is not installed.")
        print("\nPlease install dependencies first:")
        print("    pip install -r requirements.txt")
        print("\nOr install grpcio-tools directly:")
        print("    pip install grpcio-tools>=1.60.0")
        sys.exit(1)
    
    # Resolve paths
    project_root = Path(__file__).parent.parent
    proto_dir = project_root / "proto"
    output_dir = project_root / "app" / "proto_generated"
    
    # Ensure proto directory exists
    if not proto_dir.exists():
        print(f"❌ Error: Proto directory not found: {proto_dir}")
        sys.exit(1)
    
    # Find all .proto files
    proto_files = list(proto_dir.glob("*.proto"))
    if not proto_files:
        print(f"❌ Error: No .proto files found in {proto_dir}")
        sys.exit(1)
    
    print(f"📦 Found {len(proto_files)} proto file(s) to compile:")
    for proto_file in proto_files:
        print(f"   - {proto_file.name}")
    
    # Create output directory
    output_dir.mkdir(parents=True, exist_ok=True)
    
    # Create __init__.py to make it a proper Python package
    init_file = output_dir / "__init__.py"
    init_file.write_text(
        '"""Auto-generated Protocol Buffer modules.\n\n'
        'DO NOT EDIT MANUALLY.\n'
        'Generated by scripts/compile_proto.py\n'
        '"""\n'
    )
    
    # Compile each proto file
    print(f"\n🔨 Compiling Protocol Buffers...")
    for proto_file in proto_files:
        try:
            result = protoc.main([
                'protoc',
                f'--proto_path={proto_dir}',
                f'--python_out={output_dir}',
                str(proto_file),
            ])
            
            if result != 0:
                print(f"❌ Error: Failed to compile {proto_file.name}")
                sys.exit(1)
            
            print(f"   ✅ Compiled {proto_file.name}")
            
        except Exception as e:
            print(f"❌ Error compiling {proto_file.name}: {e}")
            sys.exit(1)
    
    # List generated files
    generated_files = list(output_dir.glob("*_pb2.py"))
    print(f"\n✨ Successfully generated {len(generated_files)} Python module(s):")
    for gen_file in generated_files:
        print(f"   - {gen_file.name}")
    
    print(f"\n📁 Output directory: {output_dir}")
    print("✅ Protocol Buffer compilation complete!")


if __name__ == "__main__":
    compile_proto_files()
